name: Build

on: [push]
    
jobs:
  build:
    name: Build App
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro Max']
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: | 
        xcodebuild clean build -project Vaccine\ Widgets.xcodeproj -scheme Vaccine\ Widgets\ \(iOS\) -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env: 
        destination: ${{ matrix.destination }}
